### ISSUE TITLE
很多错，这个错解决不了

### ISSUE THREAD

**Issue by liqinsg** [allan2coder/React-SPA-Tutorial#8]
> react-ssr@1.0.0 build:webpack /home/espl/react-ssr/client
> webpack --config ./config/webpack.config.prod.js

/home/espl/react-ssr/node_modules/webpack/bin/webpack.js:315
                throw e;
                ^

TypeError: Cannot read property 'make' of undefined
    at PersistentChildCompilerSingletonPlugin.apply (/home/espl/react-ssr/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:182:20)
    at new CachedChildCompilation (/home/espl/react-ssr/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:68:44)
    at HtmlWebpackPlugin.apply (/home/espl/react-ssr/node_modules/html-webpack-plugin/index.js:92:33)
    at Compiler.apply (/home/espl/react-ssr/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/espl/react-ssr/node_modules/webpack/lib/webpack.js:32:19)
    at processOptions (/home/espl/react-ssr/node_modules/webpack/bin/webpack.js:305:14)
    at Object.<anonymous> (/home/espl/react-ssr/node_modules/webpack/bin/webpack.js:363:1)

**Comment by allan2coder** [comment]
收到，改天看下。

**Comment by xxxsf** [comment]
已修复
